[common]
platform = espressif32
board = esp32dev
framework = arduino
board_build.flash_mode = dio
board_build.partitions = partitions/ota_4mb.csv
lib_deps =
    knolleary/PubSubClient
    links2004/WebSockets
    bblanchon/ArduinoJson
    adafruit/DHT sensor library
monitor_speed = 115200

[env:esp32-node-001]
extends = common
build_flags = -DNODE_ID_STR=\"esp32-node-001\" -Ikeys

[env:esp32-node-002]
extends = common
build_flags = -DNODE_ID_STR=\"esp32-node-002\" -Ikeys
